### ISSUE TITLE
Enrich the score with technical metadata

### ISSUE THREAD

**Issue by bzg** [codegouvfr/awesome-codegouvfr#11]
I suggest adding these:

- i18n: [Yes|No|N/A]
- lastSecurityAudit: [less than 1 year ago|N/A]
- themable: [Yes|No|N/A]
- a11y: [Yes|No|N/A]

For i18n, we can reuse `localisation/localisationReady` and `localisation/availableLanguages`.

For the security audits, this probably needs to be designed with projects that did some audits: what is the most useful information?

For `themable`, this is particularily relevant for DSFR (ping @garronej).

**Comment by hjonin** [comment]
FI `localisation` properties are already part of the `publiccode.yml` standard, that we can choose to implement in our format.

**Comment by bzg** [comment]
Kept as a local to-do for the script in https://git.sr.ht/~codegouvfr/codegouvfr-cli, especially the scoring part.
