### ISSUE TITLE
Publish the awesome data as json?

### ISSUE THREAD

**Issue by bzg** [codegouvfr/awesome-codegouvfr#12]
Data from the Free Software unit are published on https://code.gouv.fr/data/.

I can see how https://code.gouv.fr/data/awesome.json could be useful.

**Comment by bzg** [comment]
As discussed, let's publish the entire set of data as JSON.

**Comment by hjonin** [comment]
Now available at https://code.gouv.fr/data/awesome-codegouvfr.json
