### ISSUE TITLE
Check and improve publiccode.yml files

### ISSUE THREAD

**Issue by hjonin** [codegouvfr/awesome-codegouvfr#13]
- [ ] [ara_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/ara_publiccode.yml)
- [ ] [archifiltreDocs_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/archifiltreDocs_publiccode.yml)
- [ ] [catala_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/catala_publiccode.yml)
- [ ] [codesPostaux_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/codesPostaux_publiccode.yml)
- [ ] [contentManager_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/contentManager_publiccode.yml)
- [ ] [dashlord_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/dashlord_publiccode.yml)
- [ ] [decoupageAdministratif_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/decoupageAdministratif_publiccode.yml)
- [ ] [demarchesSimplifiees_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/demarchesSimplifiees_publiccode.yml)
- [ ] [djangoDsfr_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/djangoDsfr_publiccode.yml)
- [ ] [djangoMagicauth_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/djangoMagicauth_publiccode.yml)
- [ ] [onyxia_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/onyxia_publiccode.yml)
- [ ] [openfisca_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/openfisca_publiccode.yml)
- [ ] [publicodes_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/publicodes_publiccode.yml)
- [ ] [rdvServicePublic_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/rdvServicePublic_publiccode.yml)
- [ ] [reactDsfr_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/reactDsfr_publiccode.yml)
- [ ] [shinygouv_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/shinygouv_publiccode.yml)
- [ ] [udata_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/udata_publiccode.yml)
- [ ] [vitam_publiccode.yml](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/vitam_publiccode.yml)

**Comment by bzg** [comment]
Comment aider concrètement?

**Comment by hjonin** [comment]
We should check and fix/improve each field content of each `publiccode.yml` (e.g. add logo or metadata file if missing, add or improve French description, etc.). In fact, some fields are purely manual (e.g. logo), others may have been updated from an old synchronized version in ecosyste.ms.

**Comment by bzg** [comment]
How can potential contributors know that their manual fixes won't be overwritten by some automated fetch?

'asking for a friend 😉

**Comment by hjonin** [comment]
There is no automated fetch, everything in this repo is manual.

**Comment by bzg** [comment]
My understanding is that it was semi-manual, with some data fetched thanks to [awesome-codegouvfr-tooling](https://github.com/codegouvfr/awesome-codegouvfr-tooling).

To make my request more precise: what are the fields where changes will _never_ conflict with data produced by `awesome-codegouvfr-tooling`?

**Comment by hjonin** [comment]
No, there is no automated fetch.

The [awesome-codegouvfr-tooling](https://github.com/codegouvfr/awesome-codegouvfr-tooling) was created to generate a one-off `publiccode.yml` (with all the required fields and some data fetched from ecosyste.ms) for a given project, but it is not intended (at least in its current state) to be used continuously.

When the `publiccode.yml` is regenerated for a given project, a **new** `publiccode.yml` file is created.

I will mention this project in the README, but only so that users are aware that it exists.

**Comment by bzg** [comment]
Not relevant anymore, as `publiccode.yml` are now edited and maintained in the upstream repos.
