### ISSUE TITLE
Add filtering capacity

### ISSUE THREAD

**Issue by bzg** [codegouvfr/awesome-codegouvfr#17]
- [ ] By type of producing/funding organization (*administration centrale, collectivité, etc.*)
- [ ] By score
- [ ] ...

**Comment by hjonin** [comment]
Might be interesting to try faceted search ([an example of faceted search with eleventy/algolia](https://nicolas-hoizey.com/articles/2020/11/02/enhancing-archives-navigation-step-2/)) with [itemjs](https://github.com/itemsapi/itemsjs) - might be useful for future search capabilities for https://code.gouv.fr/public.

**Comment by hjonin** [comment]
Check also https://beta.gouv.fr/startups

**Comment by bzg** [comment]
Kept as a local to-do for https://git.sr.ht/~codegouvfr/codegouvfr-sources, closing now.
