### ISSUE TITLE
Renommer specs.md en docs.md

### ISSUE THREAD

**Issue by bzg** [codegouvfr/awesome-codegouvfr#3]
Je pense prudent d'éviter de présenter notre usage du standard publiccode.yml via des "spécifications": le mot donne l'impression qu'on veut _forker_ ce standard, alors qu'on ne fait que le respecter partiellement.

Je propose pour ça de renomme le fichier `specs.md` en `docs.md`: nous documentant les champs de publiccode.yml que nous utilisons pour décrire notre sélection de projets, ainsi que ceux que nous ajoutons (et que nous pouvons proposer pour intégration dans ce standard.)

WDYT?

**Comment by hjonin** [comment]
Je suis d'accord avec toi et qu'il vaut mieux renommer ce fichier. `docs.md` ne me convainc cependant pas tout à fait. Est-ce que `scoring.md` pourrait convenir ? Sinon `proposal.md` ? `criteria.md` ?

**Comment by bzg** [comment]
Pardon,  je suis allé trop vite dans mes précédents commits - je propose `metadata.md`.  N'hésite pas à modifier si tu veux.

**Comment by hjonin** [comment]
Pas de problème, ok pour `metadata.md` ! :)
