### ISSUE TITLE
Mise à jour de publicodes.publiccode.yml

### ISSUE THREAD

**Issue by johangirod** [codegouvfr/awesome-codegouvfr#4]
Je souhaite mettre à jour les informations manquantes suivantes [SUPPRIMER LES SECTIONS INUTILES] du fichier `[REMPLACER PAR LE NOM DE VOTRE PROJET].publiccode.yml`.

## Mainteneurs

- <Johan Girod>dev@johangirod.com
- ... à compléter

## Financements

- [Urssaf Caisse Nationale](https://lannuaire.service-public.fr/gouvernement/2ebb4281-f836-48b6-9b15-4e305d2df145)
- [Ademe](https://lannuaire.service-public.fr/gouvernement/98505403-46c6-4d6c-9766-6c58bce9a221)
- [Dinum](https://lannuaire.service-public.fr/gouvernement/d1a97841-b4bf-46df-a089-1003e4e266b4)

Cf. [annuaire du service public](https://lannuaire.service-public.fr/).

## Réutilisations

- Urssaf
- Ademe
- MTPEI
- DINUM
- ...

**Comment by hjonin** [comment]
Merci beaucoup pour ces informations ! J'ai effectué une première mise à jour dans le commit https://github.com/codegouvfr/awesome-codegouvfr/commit/1c783ed202b12d1fab22b7e998d5b3bd957e319b.

**Comment by bzg** [comment]
Je ferme cette issue traitée. Merci !
